### 1 - Loading Libraries

In [56]:
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer # Deal wirh missing values
from sklearn.compose import ColumnTransformer # Encode categorical data
from sklearn.preprocessing import OneHotEncoder # Binary Representation
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### 2 - Reading Datasets

In [58]:
# Reading dataset
dataset = pd.read_csv('inputs/Data.csv')

# Independent Variable
X = dataset.iloc[:, :-1].values #.iloc[first_line:last_line, first_column:last_column]
Y = dataset.iloc[:, -1].values
# Dependent Variable

print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Missing values treatment

In [59]:
# Dealing with missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') # Create a replace method
imputer.fit(X[:, 1:3]) # Replace missing values of columns 1 and 2 from previously rule
X[:, 1:3] = imputer.transform(X[:, 1:3]) # Replace transformed columns.

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Encoding categorical data

In [60]:
# Column transformer class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [61]:
le = LabelEncoder()
Y = le.fit_transform(Y)

print(Y)

[0 1 0 0 1 1 0 1 0 1]


### Splitting dataset: Train and Test

In [62]:
train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size = 0.2, random_state = 1)
print(train_X)
print(test_X)
print(train_Y)
print(test_Y)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


### Feature Scaling

* $Standatization = \frac{x - mean(x)}{standard deviation(x)} \in [-3,3]\$: Recomended in any situation.


* $Normalization = \frac{x - min(x)}{max(x) - min(x)} \in [0,1]$: Recomended when we have normal distribution in most of our features.

In [63]:
sc = StandardScaler()
train_X[:, 3:] = sc.fit_transform(train_X[:, 3:])
test_X[:, 3:] = sc.transform(test_X[:, 3:]) # Traanform with train mean and sd.

print(train_X)
print(test_X)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
