### Importing Libraries

In [61]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score

### Reading Dataset

In [62]:
dataset = pd.read_csv("../input/Data.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

y = y.reshape(len(y), 1)

### Splitting Training / Testing

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [64]:
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train_sc = sc_X.fit_transform(X_train)
y_train_sc = sc_y.fit_transform(y_train)

### Training Models

In [65]:
# Linear Regression Fit
linear_regressor = LinearRegression()
linear_regressor.fit(X_train, y_train)

# Polynomial Regression Fit
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
polynomial_regressor = LinearRegression()
polynomial_regressor.fit(X_poly, y_train)

# Support Vector Regressor
svr_regressor = SVR(kernel = 'rbf')
svr_regressor.fit(X_train_sc, y_train_sc)

# Decision Tree Regression
dt_regressor = DecisionTreeRegressor(random_state = 0)
dt_regressor.fit(X_train, y_train)

# Random Forest Regression
rf_regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
rf_regressor.fit(X_train, y_train)

c:\users\muril\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\muril\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:21: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

### Predicting

In [66]:
np.set_printoptions(precision=2)

# Multiple Linear Regression
y_pred_lr = linear_regressor.predict(X_test)
print("Multiple Linear Regression Prediction:")
print(np.concatenate((y_pred_lr.reshape(len(y_pred_lr),1), y_test.reshape(len(y_test),1)),1))

# Polynomial Regression
y_pred_pr = polynomial_regressor.predict(poly_reg.transform(X_test))
print("\nPolynomial Regression Prediction:")
print(np.concatenate((y_pred_pr.reshape(len(y_pred_pr),1), y_test.reshape(len(y_test),1)),1))

# Support Vector Regression
y_pred_svr = sc_y.inverse_transform(svr_regressor.predict(sc_X.transform(X_test)))
print("\nSupport Vector Regression Prediction:")
print(np.concatenate((y_pred_svr.reshape(len(y_pred_svr),1), y_test.reshape(len(y_test),1)),1))

# Decision Tree Regression
y_pred_dt = dt_regressor.predict(X_test)
print("\nDecision Tree Regression Prediction:")
print(np.concatenate((y_pred_dt.reshape(len(y_pred_dt),1), y_test.reshape(len(y_test),1)),1))


# Random Forest Regression
y_pred_rf = rf_regressor.predict(X_test)
print("\nRandom Forest Regression Prediction:")
print(np.concatenate((y_pred_rf.reshape(len(y_pred_rf),1), y_test.reshape(len(y_test),1)),1))


Multiple Linear Regression Prediction:
[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]

Polynomial Regression Prediction:
[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.67 463.28]]

Support Vector Regression Prediction:
[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]

Decision Tree Regression Prediction:
[[431.28 431.23]
 [462.81 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.55 463.28]]

Random Forest Regression Prediction:
[[433.78 431.23]
 [457.99 460.01]
 [463.14 461.14]
 ...
 [470.16 473.26]
 [439.51 438.  ]
 [460.32 463.28]]


### Performance Evaluation

In [67]:
print("Multiple Linear Regression Performance")
print(r2_score(y_test, y_pred_lr))

print("\nPolynomial Regression Performance")
print(r2_score(y_test, y_pred_pr))

print("\nSupport Vector Regression Performance")
print(r2_score(y_test, y_pred_svr))

print("\nDecision Tree Regression Performance")
print(r2_score(y_test, y_pred_dt))

print("\nRandom Forest Regression Performance")
print(r2_score(y_test, y_pred_rf))

Multiple Linear Regression Performance
0.9325315554761302

Polynomial Regression Performance
0.945819300115993

Support Vector Regression Performance
0.9480784049986258

Decision Tree Regression Performance
0.9226091050550043

Random Forest Regression Performance
0.9615980699813017
